export const DEFAULT_SETTING_DEFS = [
    // ── General ───────────────────────────────────────
    {
        key: "org_name",
        value: "Constituency Management Portal",
        type: "text",
        group: "general",
        label: "Organization Name",
        description: "Display name of the portal",
        order: 1,
    },
    {
        key: "org_short_name",
        value: "CMP",
        type: "text",
        group: "general",
        label: "Short Name / Acronym",
        description: "Used in compact UI areas",
        order: 2,
    },
    {
        key: "constituency_name",
        value: "Chandni Chowk",
        type: "text",
        group: "general",
        label: "Constituency Name",
        description: "Name of the constituency",
        order: 3,
    },
    {
        key: "constituency_type",
        value: "Parliamentary",
        type: "select",
        group: "general",
        label: "Constituency Type",
        description: "Parliamentary or Assembly",
        options: ["Parliamentary", "Assembly", "Municipal"],
        order: 4,
    },
    {
        key: "state",
        value: "Delhi",
        type: "text",
        group: "general",
        label: "State",
        description: "State name",
        order: 5,
    },
    {
        key: "district",
        value: "Central Delhi",
        type: "text",
        group: "general",
        label: "District",
        description: "District name",
        order: 6,
    },
    {
        key: "representative_name",
        value: "Shri Example Singh",
        type: "text",
        group: "general",
        label: "Representative Name",
        description: "MP/MLA name",
        order: 7,
    },
    {
        key: "representative_title",
        value: "Member of Parliament",
        type: "select",
        group: "general",
        label: "Representative Title",
        description: "Designation",
        options: [
            "Member of Parliament",
            "Member of Legislative Assembly",
            "Municipal Councillor",
            "Mayor",
            "Sarpanch",
        ],
        order: 8,
    },
    {
        key: "org_address",
        value: "Constituency Office, Main Road",
        type: "textarea",
        group: "general",
        label: "Office Address",
        description: "Physical address",
        order: 9,
    },
    {
        key: "org_phone",
        value: "+91 11 1234 5678",
        type: "text",
        group: "general",
        label: "Office Phone",
        description: "Primary contact",
        order: 10,
    },
    {
        key: "org_email",
        value: "",
        type: "text",
        group: "general",
        label: "Office Email",
        description: "Primary email — used as recipient for export/import notifications",
        order: 11,
    },
    {
        key: "org_website",
        value: "",
        type: "text",
        group: "general",
        label: "Website URL",
        description: "Official website",
        order: 12,
    },
    {
        key: "timezone",
        value: "Asia/Kolkata",
        type: "select",
        group: "general",
        label: "Timezone",
        description: "System timezone",
        options: ["Asia/Kolkata", "Asia/Colombo", "Asia/Dhaka", "Asia/Kathmandu"],
        order: 13,
    },
    {
        key: "default_language",
        value: "en",
        type: "select",
        group: "general",
        label: "Default Language",
        description: "UI language",
        options: ["en", "hi", "mr", "ta", "te", "bn", "gu", "kn", "ml", "pa", "ur"],
        order: 14,
    },
    {
        key: "financial_year_start",
        value: "April",
        type: "select",
        group: "general",
        label: "Financial Year Start",
        description: "FY start month",
        options: ["January", "April"],
        order: 15,
    },
    {
        key: "date_format",
        value: "dd/MM/yyyy",
        type: "select",
        group: "general",
        label: "Date Format",
        description: "Display format",
        options: ["dd/MM/yyyy", "MM/dd/yyyy", "yyyy-MM-dd", "dd-MMM-yyyy"],
        order: 16,
    },
    {
        key: "currency_symbol",
        value: "₹",
        type: "text",
        group: "general",
        label: "Currency Symbol",
        description: "Currency display",
        order: 17,
    },

    // ── Branding ──────────────────────────────────────
    {
        key: "brand_primary_color",
        value: "#2563eb",
        type: "color",
        group: "branding",
        label: "Primary Color",
        description: "Main theme color",
        order: 1,
    },
    {
        key: "brand_secondary_color",
        value: "#7c3aed",
        type: "color",
        group: "branding",
        label: "Secondary Color",
        description: "Accent color",
        order: 2,
    },
    {
        key: "brand_success_color",
        value: "#16a34a",
        type: "color",
        group: "branding",
        label: "Success Color",
        description: "Success/positive",
        order: 3,
    },
    {
        key: "brand_warning_color",
        value: "#d97706",
        type: "color",
        group: "branding",
        label: "Warning Color",
        description: "Warning/caution",
        order: 4,
    },
    {
        key: "brand_danger_color",
        value: "#dc2626",
        type: "color",
        group: "branding",
        label: "Danger Color",
        description: "Error/destructive",
        order: 5,
    },
    {
        key: "brand_logo_url",
        value: "",
        type: "text",
        group: "branding",
        label: "Logo URL",
        description: "Organization logo (URL or emoji)",
        order: 6,
    },
    {
        key: "brand_favicon_emoji",
        value: "🏛️",
        type: "text",
        group: "branding",
        label: "Favicon Emoji",
        description: "Browser tab icon",
        order: 7,
    },
    {
        key: "brand_sidebar_style",
        value: "default",
        type: "select",
        group: "branding",
        label: "Sidebar Style",
        description: "Navigation style",
        options: ["default", "compact", "minimal"],
        order: 8,
    },
    {
        key: "brand_login_bg",
        value: "gradient",
        type: "select",
        group: "branding",
        label: "Login Page Background",
        description: "Login screen style",
        options: ["gradient", "solid", "image"],
        order: 9,
    },
    {
        key: "brand_footer_text",
        value: "Powered by Vibrantick Infotech Solutions",
        type: "text",
        group: "branding",
        label: "Footer Text",
        description: "Shown at bottom of pages",
        order: 10,
    },

    // ── Security ──────────────────────────────────────
    {
        key: "session_timeout_minutes",
        value: "30",
        type: "number",
        group: "security",
        label: "Session Timeout (minutes)",
        description: "Auto-logout after inactivity (0 = unlimited)",
        order: 1,
    },
    {
        key: "max_failed_logins",
        value: "5",
        type: "number",
        group: "security",
        label: "Max Failed Login Attempts",
        description: "Lock account after N failures",
        order: 2,
    },
    {
        key: "lockout_duration_minutes",
        value: "15",
        type: "number",
        group: "security",
        label: "Lockout Duration (minutes)",
        description: "How long account stays locked",
        order: 3,
    },
    {
        key: "password_min_length",
        value: "8",
        type: "number",
        group: "security",
        label: "Min Password Length",
        description: "Minimum characters required",
        order: 4,
    },
    {
        key: "password_require_uppercase",
        value: "true",
        type: "boolean",
        group: "security",
        label: "Require Uppercase",
        description: "At least one uppercase letter",
        order: 5,
    },
    {
        key: "password_require_number",
        value: "true",
        type: "boolean",
        group: "security",
        label: "Require Number",
        description: "At least one digit",
        order: 6,
    },
    {
        key: "password_require_special",
        value: "true",
        type: "boolean",
        group: "security",
        label: "Require Special Character",
        description: "At least one special char",
        order: 7,
    },
    {
        key: "password_expiry_days",
        value: "90",
        type: "number",
        group: "security",
        label: "Password Expiry (days)",
        description: "Force change after N days (0=never)",
        order: 8,
    },
    {
        key: "allowed_ip_ranges",
        value: "",
        type: "textarea",
        group: "security",
        label: "Allowed IP Ranges",
        description: "Restrict access by IP (one per line, blank=all)",
        order: 9,
    },
    {
        key: "enable_audit_log",
        value: "true",
        type: "boolean",
        group: "security",
        label: "Enable Audit Logging",
        description: "Track all user actions",
        order: 10,
    },

    // ── Grievance ─────────────────────────────────────
    {
        key: "grievance_sla_days",
        value: "7",
        type: "number",
        group: "grievance",
        label: "Default SLA (days)",
        description: "Expected resolution time",
        order: 1,
    },
    {
        key: "grievance_auto_assign",
        value: "false",
        type: "boolean",
        group: "grievance",
        label: "Auto-Assign by Category",
        description: "Auto-assign to department",
        order: 2,
    },
    {
        key: "grievance_escalation_days",
        value: "3",
        type: "number",
        group: "grievance",
        label: "Auto Escalation (days)",
        description: "Escalate if not acted upon",
        order: 3,
    },
    {
        key: "grievance_allow_anonymous",
        value: "false",
        type: "boolean",
        group: "grievance",
        label: "Allow Anonymous Complaints",
        description: "Accept without citizen name",
        order: 4,
    },
    {
        key: "grievance_require_phone",
        value: "true",
        type: "boolean",
        group: "grievance",
        label: "Require Phone Number",
        description: "Mandatory phone for tracking",
        order: 5,
    },
    {
        key: "grievance_ticket_prefix",
        value: "GRV",
        type: "text",
        group: "grievance",
        label: "Ticket Number Prefix",
        description: "e.g. GRV-2025-00001",
        order: 6,
    },
    {
        key: "grievance_categories",
        value:
            "Water Supply,Road Damage,Electricity,Sanitation,Drainage,Street Light,Health,Education,Law & Order,Encroachment,Noise,Other",
        type: "textarea",
        group: "grievance",
        label: "Grievance Categories",
        description: "Comma-separated list",
        order: 7,
    },
    {
        key: "grievance_sources",
        value: "WALK_IN,PHONE,EMAIL,WHATSAPP,SOCIAL_MEDIA,CAMP,REFERRAL,ONLINE",
        type: "textarea",
        group: "grievance",
        label: "Grievance Sources",
        description: "Comma-separated intake channels",
        order: 8,
    },

    // ── Notifications ─────────────────────────────────
    {
        key: "sms_enabled",
        value: "false",
        type: "boolean",
        group: "notifications",
        label: "SMS Enabled",
        description: "Send SMS notifications",
        order: 1,
    },
    {
        key: "sms_provider",
        value: "twilio",
        type: "select",
        group: "notifications",
        label: "SMS Provider",
        description: "Gateway provider",
        options: ["twilio", "msg91", "textlocal", "fast2sms", "custom"],
        order: 2,
    },
    {
        key: "sms_api_key",
        value: "",
        type: "secret",
        group: "notifications",
        label: "SMS API Key",
        description: "Provider API key",
        isSecret: true,
        order: 3,
    },
    {
        key: "sms_sender_id",
        value: "CONSTY",
        type: "text",
        group: "notifications",
        label: "SMS Sender ID",
        description: "6-char sender ID",
        order: 4,
    },
    {
        key: "whatsapp_enabled",
        value: "false",
        type: "boolean",
        group: "notifications",
        label: "WhatsApp Enabled",
        description: "Send WhatsApp messages",
        order: 5,
    },
    {
        key: "whatsapp_api_key",
        value: "",
        type: "secret",
        group: "notifications",
        label: "WhatsApp API Key",
        description: "WhatsApp Business API key",
        isSecret: true,
        order: 6,
    },
    {
        key: "notify_on_grievance_create",
        value: "true",
        type: "boolean",
        group: "notifications",
        label: "Notify on Grievance Filed",
        description: "Send confirmation to citizen",
        order: 7,
    },
    {
        key: "notify_on_grievance_resolve",
        value: "true",
        type: "boolean",
        group: "notifications",
        label: "Notify on Grievance Resolved",
        description: "Send resolution notice",
        order: 8,
    },
    {
        key: "notify_birthday_reminder",
        value: "true",
        type: "boolean",
        group: "notifications",
        label: "Birthday Reminders",
        description: "Daily leader birthday alerts",
        order: 9,
    },
    // ── Email & SMTP ──────────────────────────────────
    {
        key: "email_enabled",
        value: "false",
        type: "boolean",
        group: "email_smtp",
        label: "Email Enabled",
        description: "Send email notifications",
        order: 1,
    },
    {
        key: "email_from",
        value: "",
        type: "text",
        group: "email_smtp",
        label: "From Email",
        description: "Sender email address",
        order: 2,
    },
    {
        key: "smtp_host",
        value: "smtp.gmail.com",
        type: "text",
        group: "email_smtp",
        label: "SMTP Host",
        description: "Mail server host",
        order: 3,
    },
    {
        key: "smtp_port",
        value: "465",
        type: "number",
        group: "email_smtp",
        label: "SMTP Port",
        description: "Mail server port",
        order: 4,
    },
    {
        key: "smtp_user",
        value: "",
        type: "text",
        group: "email_smtp",
        label: "SMTP Username",
        description: "Mail server login",
        order: 5,
    },
    {
        key: "smtp_password",
        value: "ijdf sqcw gpbz qyqq",
        type: "secret",
        group: "email_smtp",
        label: "SMTP Password",
        description: "Mail server password",
        isSecret: true,
        order: 6,
    },
    {
        key: "notify_on_export_import",
        value: "true",
        type: "boolean",
        group: "email_smtp",
        label: "Notify on Export/Import",
        description: "Send admin email when data is exported or imported",
        order: 7,
    },

    // ── Backup ────────────────────────────────────────
    {
        key: "backup_enabled",
        value: "false",
        type: "boolean",
        group: "backup",
        label: "Auto Backup",
        description: "Enable scheduled backups",
        order: 1,
    },
    {
        key: "backup_frequency",
        value: "daily",
        type: "select",
        group: "backup",
        label: "Backup Frequency",
        description: "How often to backup",
        options: ["hourly", "daily", "weekly", "monthly"],
        order: 2,
    },
    {
        key: "backup_time",
        value: "02:00",
        type: "text",
        group: "backup",
        label: "Backup Time",
        description: "Scheduled time (24h)",
        order: 3,
    },
    {
        key: "backup_retention_days",
        value: "30",
        type: "number",
        group: "backup",
        label: "Retention (days)",
        description: "Keep backups for N days",
        order: 4,
    },
    {
        key: "backup_storage",
        value: "local",
        type: "select",
        group: "backup",
        label: "Storage Location",
        description: "Where to store backups",
        options: ["local", "s3", "gcs", "azure"],
        order: 5,
    },

    // ── Meetings ──────────────────────────────────────
    {
        key: "meeting_reminder_hours",
        value: "4",
        type: "number",
        group: "meetings",
        label: "Meeting Reminder (hours)",
        description: "Hours before meeting to send email notification",
        order: 1,
    },
    {
        key: "meeting_reminder_enabled",
        value: "true",
        type: "boolean",
        group: "meetings",
        label: "Enable Meeting Reminders",
        description: "Automatically send reminder emails for scheduled meetings",
        order: 2,
    },
];
