export const DEFAULT_SETTING_DEFS = [
  // ── General ───────────────────────────────────────
  {
    key: "org_name",
    value: "Online Exam Platform",
    type: "text",
    group: "general",
    label: "Organization Name",
    description: "Display name of the platform",
    order: 1,
  },
  {
    key: "org_short_name",
    value: "OEP",
    type: "text",
    group: "general",
    label: "Short Name / Acronym",
    description: "Used in compact UI areas",
    order: 2,
  },
  {
    key: "org_address",
    value: "",
    type: "textarea",
    group: "general",
    label: "Office Address",
    description: "Physical address of the organization",
    order: 3,
  },
  {
    key: "org_phone",
    value: "",
    type: "text",
    group: "general",
    label: "Office Phone",
    description: "Primary contact number",
    order: 4,
  },
  {
    key: "org_email",
    value: "",
    type: "text",
    group: "general",
    label: "Office Email",
    description:
      "Primary email — used as recipient for export/import notifications",
    order: 5,
  },
  {
    key: "org_website",
    value: "",
    type: "text",
    group: "general",
    label: "Website URL",
    description: "Official website",
    order: 6,
  },
  {
    key: "timezone",
    value: "Asia/Kolkata",
    type: "select",
    group: "general",
    label: "Timezone",
    description: "System timezone",
    options: ["Asia/Kolkata", "Asia/Colombo", "Asia/Dhaka", "Asia/Kathmandu", "UTC", "America/New_York", "Europe/London"],
    order: 7,
  },

  // ── Branding ──────────────────────────────────────
  {
    key: "brand_primary_color",
    value: "#2563eb",
    type: "color",
    group: "branding",
    label: "Primary Color",
    description: "Main theme color",
    order: 1,
  },
  {
    key: "brand_secondary_color",
    value: "#7c3aed",
    type: "color",
    group: "branding",
    label: "Secondary Color",
    description: "Accent color",
    order: 2,
  },
  {
    key: "brand_success_color",
    value: "#16a34a",
    type: "color",
    group: "branding",
    label: "Success Color",
    description: "Success/positive",
    order: 3,
  },
  {
    key: "brand_warning_color",
    value: "#d97706",
    type: "color",
    group: "branding",
    label: "Warning Color",
    description: "Warning/caution",
    order: 4,
  },
  {
    key: "brand_danger_color",
    value: "#dc2626",
    type: "color",
    group: "branding",
    label: "Danger Color",
    description: "Error/destructive",
    order: 5,
  },
  {
    key: "brand_logo_url",
    value: "",
    type: "image",
    group: "branding",
    label: "Dashboard Logo",
    description: "Uploaded logo used in the admin sidebar and login page",
    order: 6,
  },
  {
    key: "brand_favicon_url",
    value: "",
    type: "image",
    group: "branding",
    label: "Dashboard Favicon",
    description: "Uploaded favicon used in the browser tab",
    order: 7,
  },
  {
    key: "brand_sidebar_style",
    value: "default",
    type: "select",
    group: "branding",
    label: "Sidebar Style",
    description: "Navigation style",
    options: ["default", "compact", "minimal"],
    order: 8,
  },
  {
    key: "brand_login_bg",
    value: "gradient",
    type: "select",
    group: "branding",
    label: "Login Page Background",
    description: "Login screen style",
    options: ["gradient", "solid", "image"],
    order: 9,
  },
  {
    key: "brand_footer_text",
    value: "Online Exam Platform",
    type: "text",
    group: "branding",
    label: "Footer Text",
    description: "Shown at bottom of dashboard pages",
    order: 10,
  },

  // ── Website General ────────────────────────────────
  {
    key: "website_site_name",
    value: "Online Exam Platform",
    type: "text",
    group: "website_general",
    label: "Website Name",
    description: "Frontend public website brand name",
    order: 1,
  },
  {
    key: "website_tagline",
    value: "Your gateway to online assessments and certifications",
    type: "text",
    group: "website_general",
    label: "Website Tagline",
    description: "Short public tagline for hero/footer/SEO use",
    order: 2,
  },
  {
    key: "website_logo_url",
    value: "",
    type: "image",
    group: "website_general",
    label: "Website Logo",
    description: "Uploaded logo used on the public website",
    order: 3,
  },
  {
    key: "website_favicon_url",
    value: "",
    type: "image",
    group: "website_general",
    label: "Website Favicon",
    description: "Uploaded favicon used on the public website",
    order: 4,
  },
  {
    key: "website_primary_cta_text",
    value: "Start Exam",
    type: "text",
    group: "website_general",
    label: "Primary CTA Text",
    description: "Default website call-to-action label",
    order: 5,
  },
  {
    key: "website_primary_cta_link",
    value: "/login",
    type: "text",
    group: "website_general",
    label: "Primary CTA Link",
    description: "Default website call-to-action target",
    order: 6,
  },

  // ── Website Contact ────────────────────────────────
  {
    key: "website_contact_title",
    value: "Get in touch",
    type: "text",
    group: "website_contact",
    label: "Contact Section Title",
    description: "Heading used on contact sections/pages",
    order: 1,
  },
  {
    key: "website_contact_description",
    value: "Have questions about our exams? Reach out to us for support.",
    type: "textarea",
    group: "website_contact",
    label: "Contact Description",
    description: "Short helper text for the contact section",
    order: 2,
  },
  {
    key: "website_contact_phone",
    value: "",
    type: "text",
    group: "website_contact",
    label: "Public Phone",
    description: "Phone number shown on the website",
    order: 3,
  },
  {
    key: "website_contact_email",
    value: "",
    type: "text",
    group: "website_contact",
    label: "Public Email",
    description: "Email shown on the website",
    order: 4,
  },
  {
    key: "website_contact_whatsapp",
    value: "",
    type: "text",
    group: "website_contact",
    label: "WhatsApp Number",
    description: "Optional WhatsApp number in international format",
    order: 5,
  },
  {
    key: "website_contact_address",
    value: "",
    type: "textarea",
    group: "website_contact",
    label: "Public Address",
    description: "Address displayed on contact/footer sections",
    order: 6,
  },
  {
    key: "website_contact_map_embed_url",
    value: "",
    type: "textarea",
    group: "website_contact",
    label: "Map Embed URL",
    description: "Use the Google Maps embed URL or trusted iframe src only",
    order: 7,
  },
  {
    key: "website_contact_working_hours",
    value: "Mon-Sat, 10:00 AM - 6:00 PM",
    type: "text",
    group: "website_contact",
    label: "Working Hours",
    description: "Public office timing",
    order: 8,
  },

  // ── Website Footer ─────────────────────────────────
  {
    key: "website_footer_copyright",
    value: "Online Exam Platform. All rights reserved.",
    type: "text",
    group: "website_footer",
    label: "Footer Copyright",
    description: "Bottom-most copyright line",
    order: 1,
  },
  {
    key: "website_footer_about",
    value:
      "A comprehensive online assessment platform for students and institutions.",
    type: "textarea",
    group: "website_footer",
    label: "Footer About Text",
    description: "Short footer description about the platform",
    order: 2,
  },
  {
    key: "website_footer_links_json",
    value:
      '[{"label":"Home","href":"/"},{"label":"Courses","href":"/courses"},{"label":"About","href":"/about"},{"label":"Contact","href":"/contact"}]',
    type: "textarea",
    group: "website_footer",
    label: "Footer Links JSON",
    description: "JSON array of footer links with label and href",
    order: 3,
  },
  {
    key: "website_social_links_json",
    value: '{"facebook":"","instagram":"","linkedin":"","youtube":"","x":""}',
    type: "textarea",
    group: "website_footer",
    label: "Social Links JSON",
    description: "JSON object of public social links",
    order: 4,
  },

  // ── Website About ──────────────────────────────────
  {
    key: "website_about_title",
    value: "About Us",
    type: "text",
    group: "website_about",
    label: "Main Title",
    description: "Primary heading for the about page/section",
    order: 1,
  },
  {
    key: "website_about_subtitle",
    value: "Who we are",
    type: "text",
    group: "website_about",
    label: "Subtitle",
    description: "Short supporting label shown above or near the title",
    order: 2,
  },
  {
    key: "website_about_summary",
    value:
      "We provide a robust online examination platform for educational institutions and organizations.",
    type: "textarea",
    group: "website_about",
    label: "Description",
    description: "Short descriptive copy for the about section",
    order: 3,
  },
  {
    key: "website_about_content",
    value:
      "<p>Our platform enables seamless online assessments with features like timed tests, auto-grading, detailed analytics, and much more.</p>",
    type: "textarea",
    group: "website_about",
    label: "About Content",
    description: "Rich text or HTML content for the full about page",
    order: 4,
  },
  {
    key: "website_about_image_1",
    value: "",
    type: "image",
    group: "website_about",
    label: "Image 1",
    description: "Primary image for the about section",
    order: 5,
  },
  {
    key: "website_about_image_2",
    value: "",
    type: "image",
    group: "website_about",
    label: "Image 2",
    description: "Secondary image for the about section",
    order: 6,
  },
  {
    key: "website_about_experience_years",
    value: "10",
    type: "number",
    group: "website_about",
    label: "Years of Experience",
    description: "Counter value shown for years of experience",
    order: 7,
  },

  // ── Website Why Choose Us ──────────────────────────
  {
    key: "website_why_choose_us_title",
    value: "Why Choose Us",
    type: "text",
    group: "website_why_choose_us",
    label: "Section Title",
    description: "Main heading for the Why Choose Us section",
    order: 1,
  },
  {
    key: "website_why_choose_us_subtitle",
    value: "Built to help learners move faster with confidence",
    type: "text",
    group: "website_why_choose_us",
    label: "Section Subtitle",
    description: "Short supporting line shown near the title",
    order: 2,
  },
  {
    key: "website_why_choose_us_description",
    value:
      "Highlight what makes your institute or platform different, credible, and worth choosing.",
    type: "textarea",
    group: "website_why_choose_us",
    label: "Section Description",
    description: "Primary descriptive copy for the section",
    order: 3,
  },
  {
    key: "website_why_choose_us_key_points_json",
    value:
      '["Expert mentors and practical guidance","Industry-focused curriculum and projects","Supportive learning environment with real outcomes"]',
    type: "textarea",
    group: "website_why_choose_us",
    label: "Key Points JSON",
    description: "JSON array of short key points shown as bullets or highlights",
    order: 4,
  },
  {
    key: "website_why_choose_us_image_1",
    value: "",
    type: "image",
    group: "website_why_choose_us",
    label: "Image 1",
    description: "Primary image for the Why Choose Us section",
    order: 5,
  },
  {
    key: "website_why_choose_us_image_2",
    value: "",
    type: "image",
    group: "website_why_choose_us",
    label: "Image 2",
    description: "Secondary image for the Why Choose Us section",
    order: 6,
  },

  // ── SEO ────────────────────────────────────────────
  {
    key: "seo_default_meta_title",
    value: "Online Exam Platform",
    type: "text",
    group: "seo",
    label: "Default Meta Title",
    description: "Fallback title for pages without a custom SEO title",
    order: 1,
  },
  {
    key: "seo_default_meta_description",
    value:
      "Take online exams, practice tests, and get certified — all in one platform.",
    type: "textarea",
    group: "seo",
    label: "Default Meta Description",
    description: "Fallback description for search and social previews",
    order: 2,
  },
  {
    key: "seo_default_og_image",
    value: "",
    type: "text",
    group: "seo",
    label: "Default OG Image",
    description: "Fallback Open Graph image URL",
    order: 3,
  },
  {
    key: "seo_home_meta_title",
    value: "Home | Online Exam Platform",
    type: "text",
    group: "seo",
    label: "Home Meta Title",
    description: "SEO title for homepage",
    order: 4,
  },
  {
    key: "seo_home_meta_description",
    value:
      "Explore courses, take practice tests, and prepare for your certifications online.",
    type: "textarea",
    group: "seo",
    label: "Home Meta Description",
    description: "SEO description for homepage",
    order: 5,
  },
  {
    key: "seo_about_meta_title",
    value: "About Us | Online Exam Platform",
    type: "text",
    group: "seo",
    label: "About Meta Title",
    description: "SEO title for the about page",
    order: 6,
  },
  {
    key: "seo_about_meta_description",
    value:
      "Learn about our mission to make quality online assessments accessible to everyone.",
    type: "textarea",
    group: "seo",
    label: "About Meta Description",
    description: "SEO description for the about page",
    order: 7,
  },
  {
    key: "seo_contact_meta_title",
    value: "Contact Us | Online Exam Platform",
    type: "text",
    group: "seo",
    label: "Contact Meta Title",
    description: "SEO title for the contact page",
    order: 8,
  },
  {
    key: "seo_contact_meta_description",
    value:
      "Contact our support team for help with exams, courses, or technical issues.",
    type: "textarea",
    group: "seo",
    label: "Contact Meta Description",
    description: "SEO description for the contact page",
    order: 9,
  },

  // ── Security ──────────────────────────────────────
  {
    key: "session_timeout_minutes",
    value: "30",
    type: "number",
    group: "security",
    label: "Session Timeout (minutes)",
    description: "Auto-logout after inactivity (0 = unlimited)",
    order: 1,
  },
  {
    key: "max_failed_logins",
    value: "5",
    type: "number",
    group: "security",
    label: "Max Failed Login Attempts",
    description: "Lock account after N failures",
    order: 2,
  },
  {
    key: "lockout_duration_minutes",
    value: "15",
    type: "number",
    group: "security",
    label: "Lockout Duration (minutes)",
    description: "How long account stays locked",
    order: 3,
  },
  {
    key: "password_min_length",
    value: "8",
    type: "number",
    group: "security",
    label: "Min Password Length",
    description: "Minimum characters required",
    order: 4,
  },
  {
    key: "password_require_uppercase",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Require Uppercase",
    description: "At least one uppercase letter",
    order: 5,
  },
  {
    key: "password_require_number",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Require Number",
    description: "At least one digit",
    order: 6,
  },
  {
    key: "password_require_special",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Require Special Character",
    description: "At least one special char",
    order: 7,
  },
  {
    key: "password_expiry_days",
    value: "90",
    type: "number",
    group: "security",
    label: "Password Expiry (days)",
    description: "Force change after N days (0=never)",
    order: 8,
  },
  {
    key: "allowed_ip_ranges",
    value: "",
    type: "textarea",
    group: "security",
    label: "Allowed IP Ranges",
    description: "Restrict access by IP (one per line, blank=all)",
    order: 9,
  },
  {
    key: "enable_audit_log",
    value: "true",
    type: "boolean",
    group: "security",
    label: "Enable Audit Logging",
    description: "Track all user actions",
    order: 10,
  },

  // ── Notifications ─────────────────────────────────
  {
    key: "sms_enabled",
    value: "false",
    type: "boolean",
    group: "notifications",
    label: "SMS Enabled",
    description: "Send SMS notifications",
    order: 1,
  },
  {
    key: "sms_provider",
    value: "twilio",
    type: "select",
    group: "notifications",
    label: "SMS Provider",
    description: "Gateway provider",
    options: ["twilio", "msg91", "textlocal", "fast2sms", "custom"],
    order: 2,
  },
  {
    key: "sms_api_key",
    value: "",
    type: "secret",
    group: "notifications",
    label: "SMS API Key",
    description: "Provider API key",
    isSecret: true,
    order: 3,
  },
  {
    key: "sms_sender_id",
    value: "EXMPLF",
    type: "text",
    group: "notifications",
    label: "SMS Sender ID",
    description: "6-char sender ID",
    order: 4,
  },
  {
    key: "whatsapp_enabled",
    value: "false",
    type: "boolean",
    group: "notifications",
    label: "WhatsApp Enabled",
    description: "Send WhatsApp messages",
    order: 5,
  },
  {
    key: "whatsapp_api_key",
    value: "",
    type: "secret",
    group: "notifications",
    label: "WhatsApp API Key",
    description: "WhatsApp Business API key",
    isSecret: true,
    order: 6,
  },
  {
    key: "notify_on_exam_submit",
    value: "true",
    type: "boolean",
    group: "notifications",
    label: "Notify on Exam Submission",
    description: "Send confirmation to student after exam submission",
    order: 7,
  },
  {
    key: "notify_on_result_publish",
    value: "true",
    type: "boolean",
    group: "notifications",
    label: "Notify on Result Published",
    description: "Notify students when results are published",
    order: 8,
  },
  {
    key: "notify_on_new_test",
    value: "true",
    type: "boolean",
    group: "notifications",
    label: "Notify on New Test Available",
    description: "Notify enrolled students when a new test is published",
    order: 9,
  },

  // ── Email & SMTP ──────────────────────────────────
  {
    key: "email_enabled",
    value: "false",
    type: "boolean",
    group: "email_smtp",
    label: "Email Enabled",
    description: "Send email notifications",
    order: 1,
  },
  {
    key: "email_from",
    value: "",
    type: "text",
    group: "email_smtp",
    label: "From Email",
    description: "Sender email address",
    order: 2,
  },
  {
    key: "smtp_host",
    value: "smtp.gmail.com",
    type: "text",
    group: "email_smtp",
    label: "SMTP Host",
    description: "Mail server host",
    order: 3,
  },
  {
    key: "smtp_port",
    value: "465",
    type: "number",
    group: "email_smtp",
    label: "SMTP Port",
    description: "Mail server port",
    order: 4,
  },
  {
    key: "smtp_user",
    value: "",
    type: "text",
    group: "email_smtp",
    label: "SMTP Username",
    description: "Mail server login",
    order: 5,
  },
  {
    key: "smtp_password",
    value: "",
    type: "secret",
    group: "email_smtp",
    label: "SMTP Password",
    description: "Mail server password",
    isSecret: true,
    order: 6,
  },
  {
    key: "notify_on_export_import",
    value: "true",
    type: "boolean",
    group: "email_smtp",
    label: "Notify on Export/Import",
    description: "Send admin email when data is exported or imported",
    order: 7,
  },

  // ── Backup ────────────────────────────────────────
  {
    key: "backup_enabled",
    value: "false",
    type: "boolean",
    group: "backup",
    label: "Auto Backup",
    description: "Enable scheduled backups",
    order: 1,
  },
  {
    key: "backup_frequency",
    value: "daily",
    type: "select",
    group: "backup",
    label: "Backup Frequency",
    description: "How often to backup",
    options: ["hourly", "daily", "weekly", "monthly"],
    order: 2,
  },
  {
    key: "backup_time",
    value: "02:00",
    type: "text",
    group: "backup",
    label: "Backup Time",
    description: "Scheduled time (24h)",
    order: 3,
  },
  {
    key: "backup_retention_days",
    value: "30",
    type: "number",
    group: "backup",
    label: "Retention (days)",
    description: "Keep backups for N days",
    order: 4,
  },
  {
    key: "backup_storage",
    value: "local",
    type: "select",
    group: "backup",
    label: "Storage Location",
    description: "Where to store backups",
    options: ["local", "s3", "gcs", "azure"],
    order: 5,
  },
];
