export const MOCK_DATA = {
  user: {
    name: "Rajesh Kumar",
    role: "MLA",
    constituency: "South Bengaluru",
    avatar:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80",
  },
  stats: [
    {
      label: "Total Grievances",
      value: 1248,
      trend: "+12%",
      status: "neutral",
    },
    { label: "Resolved (Month)", value: 86, trend: "+5%", status: "success" },
    {
      label: "Active Projects",
      value: 14,
      trend: "3 Delayed",
      status: "warning",
    },
    {
      label: "Projects Completed",
      value: 42,
      trend: "This Year",
      status: "neutral",
    },
    { label: "Institutions", value: 156, trend: "Tracked", status: "neutral" },
    {
      label: "Avg Resolution",
      value: "4.2 Days",
      trend: "-0.5 Days",
      status: "success",
    },
  ],
  recentGrievances: [
    {
      id: "GRV-2024-001",
      citizen: "Amit Sharma",
      category: "Road",
      ward: "Ward 12",
      status: "Pending",
      priority: "High",
      date: "2024-02-15",
    },
    {
      id: "GRV-2024-002",
      citizen: "Priya Singh",
      category: "Water",
      ward: "Ward 08",
      status: "In Progress",
      priority: "Medium",
      date: "2024-02-14",
    },
    {
      id: "GRV-2024-003",
      citizen: "Rahul Verma",
      category: "Electricity",
      ward: "Ward 15",
      status: "Resolved",
      priority: "Low",
      date: "2024-02-12",
    },
    {
      id: "GRV-2024-004",
      citizen: "Sneha Gupta",
      category: "Sanitation",
      ward: "Ward 03",
      status: "Pending",
      priority: "High",
      date: "2024-02-10",
    },
    {
      id: "GRV-2024-005",
      citizen: "Vikram Malhotra",
      category: "Health",
      ward: "Ward 22",
      status: "In Progress",
      priority: "Critical",
      date: "2024-02-09",
    },
  ],
  projects: [
    {
      id: 1,
      name: "Road Resurfacing - MG Road",
      budget: "₹1.2 Cr",
      progress: 75,
      status: "Running",
      ward: "Ward 05",
    },
    {
      id: 2,
      name: "Community Hall Renovation",
      budget: "₹45 L",
      progress: 30,
      status: "Running",
      ward: "Ward 12",
    },
    {
      id: 3,
      name: "New Park Development",
      budget: "₹80 L",
      progress: 0,
      status: "Pending",
      ward: "Ward 18",
    },
    {
      id: 4,
      name: "Street Light Installation",
      budget: "₹25 L",
      progress: 100,
      status: "Completed",
      ward: "Ward 02",
    },
    {
      id: 5,
      name: "Drainage Repair",
      budget: "₹15 L",
      progress: 10,
      status: "On Hold",
      ward: "Ward 09",
    },
  ],
};

import {
  User,
  Ward,
  Area,
  Grievance,
  Project,
  Institution,
  // Scheme,
  Notification,
} from "./types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Rajesh Kumar",
    email: "admin@constituency.gov.in",
    role: "super_admin",
    phone: "9876543210",
    is_active: true,
  },
  {
    id: "u2",
    name: "Shri Ramesh Sharma",
    email: "mla@constituency.gov.in",
    role: "mla",
    phone: "9876543211",
    is_active: true,
  },
  {
    id: "u3",
    name: "Priya Gupta",
    email: "priya@constituency.gov.in",
    role: "staff",
    phone: "9876543212",
    is_active: true,
  },
  {
    id: "u4",
    name: "Amit Verma",
    email: "amit@constituency.gov.in",
    role: "staff",
    phone: "9876543213",
    is_active: true,
  },
  {
    id: "u5",
    name: "Sanjay Tiwari",
    email: "sanjay@constituency.gov.in",
    role: "staff",
    phone: "9876543214",
    is_active: true,
  },
  {
    id: "u6",
    name: "Neha Agarwal",
    email: "neha@constituency.gov.in",
    role: "staff",
    phone: "9876543215",
    is_active: false,
  },
  {
    id: "u7",
    name: "Ravi Shankar",
    email: "ravi@constituency.gov.in",
    role: "staff",
    phone: "9876543216",
    is_active: true,
  },
  {
    id: "u8",
    name: "Pooja Mishra",
    email: "pooja@constituency.gov.in",
    role: "staff",
    phone: "9876543217",
    is_active: true,
  },
];

export const MOCK_WARDS: Ward[] = [
  {
    ward_id: "w1",
    ward_name: "Shivaji Nagar",
    ward_number: 1,
    population: 28500,
    area_type: "urban",
    zone: "Zone A",
    councillor_name: "Suresh Patil",
    councillor_phone: "9876000001",
    total_households: 5700,
    status: "active",
    created_date: "2020-01-15",
    description: "Major commercial and residential ward in central area",
  },
  {
    ward_id: "w2",
    ward_name: "Gandhi Chowk",
    ward_number: 2,
    population: 32100,
    area_type: "urban",
    zone: "Zone A",
    councillor_name: "Meera Joshi",
    councillor_phone: "9876000002",
    total_households: 6420,
    status: "active",
    created_date: "2020-01-15",
    description: "Historic market area with dense population",
  },
  {
    ward_id: "w3",
    ward_name: "Nehru Colony",
    ward_number: 3,
    population: 19800,
    area_type: "semi-urban",
    zone: "Zone B",
    councillor_name: "Ramesh Yadav",
    councillor_phone: "9876000003",
    total_households: 3960,
    status: "active",
    created_date: "2020-01-15",
    description: "Developing area with new residential colonies",
  },
  {
    ward_id: "w4",
    ward_name: "Ambedkar Nagar",
    ward_number: 4,
    population: 24600,
    area_type: "urban",
    zone: "Zone B",
    councillor_name: "Sunita Kumari",
    councillor_phone: "9876000004",
    total_households: 4920,
    status: "active",
    created_date: "2020-01-15",
    description: "Densely populated residential ward",
  },
  {
    ward_id: "w5",
    ward_name: "Patel Ward",
    ward_number: 5,
    population: 15200,
    area_type: "rural",
    zone: "Zone C",
    councillor_name: "Bhagwan Das",
    councillor_phone: "9876000005",
    total_households: 3040,
    status: "active",
    created_date: "2020-01-15",
    description: "Agricultural area with scattered villages",
  },
  {
    ward_id: "w6",
    ward_name: "Subhash Mohalla",
    ward_number: 6,
    population: 21300,
    area_type: "semi-urban",
    zone: "Zone C",
    councillor_name: "Asha Devi",
    councillor_phone: "9876000006",
    total_households: 4260,
    status: "active",
    created_date: "2020-01-15",
    description: "Mixed residential and small business area",
  },
  {
    ward_id: "w7",
    ward_name: "Rajendra Nagar",
    ward_number: 7,
    population: 27400,
    area_type: "urban",
    zone: "Zone D",
    councillor_name: "Vikram Singh",
    councillor_phone: "9876000007",
    total_households: 5480,
    status: "active",
    created_date: "2020-01-15",
    description: "Upscale residential area with parks",
  },
  {
    ward_id: "w8",
    ward_name: "Tilak Vihar",
    ward_number: 8,
    population: 18900,
    area_type: "semi-urban",
    zone: "Zone D",
    councillor_name: "Kavita Sharma",
    councillor_phone: "9876000008",
    total_households: 3780,
    status: "active",
    created_date: "2020-01-15",
    description: "Transitional area with growing infrastructure",
  },
  {
    ward_id: "w9",
    ward_name: "Sarojini Enclave",
    ward_number: 9,
    population: 22700,
    area_type: "urban",
    zone: "Zone A",
    councillor_name: "Neeraj Gupta",
    councillor_phone: "9876000009",
    total_households: 4540,
    status: "active",
    created_date: "2020-01-15",
    description: "Modern residential enclave with amenities",
  },
  {
    ward_id: "w10",
    ward_name: "Bhagat Singh Colony",
    ward_number: 10,
    population: 16800,
    area_type: "rural",
    zone: "Zone C",
    councillor_name: "Dharamvir Pal",
    councillor_phone: "9876000010",
    total_households: 3360,
    status: "active",
    created_date: "2020-01-15",
    description: "Rural colony with agricultural land",
  },
];

export const MOCK_AREAS: Area[] = [
  {
    area_id: "a1",
    area_name: "Market Road",
    area_type: "urban",
    population: 8500,
    ward_id: "w1",
    pincode: "201001",
    landmark: "Near Main Market",
    households: 1700,
  },
  {
    area_id: "a2",
    area_name: "Temple Street",
    area_type: "urban",
    population: 6200,
    ward_id: "w1",
    pincode: "201001",
    landmark: "Shri Ram Mandir",
    households: 1240,
  },
  {
    area_id: "a3",
    area_name: "Civil Lines",
    area_type: "urban",
    population: 7400,
    ward_id: "w1",
    pincode: "201002",
    landmark: "District Court",
    households: 1480,
  },
  {
    area_id: "a4",
    area_name: "Nehru Market",
    area_type: "urban",
    population: 5800,
    ward_id: "w1",
    pincode: "201001",
    households: 1280,
  },
  {
    area_id: "a5",
    area_name: "Old Town",
    area_type: "urban",
    population: 9800,
    ward_id: "w2",
    pincode: "201003",
    landmark: "Clock Tower",
    households: 1960,
  },
  {
    area_id: "a6",
    area_name: "Bazaar Lane",
    area_type: "urban",
    population: 7200,
    ward_id: "w2",
    pincode: "201003",
    landmark: "Gandhi Statue",
    households: 1440,
  },
  {
    area_id: "a7",
    area_name: "Station Area",
    area_type: "urban",
    population: 8100,
    ward_id: "w2",
    pincode: "201004",
    landmark: "Railway Station",
    households: 1620,
  },
  {
    area_id: "a8",
    area_name: "Lal Bagh",
    area_type: "urban",
    population: 7000,
    ward_id: "w2",
    pincode: "201003",
    households: 1400,
  },
  {
    area_id: "a9",
    area_name: "Sector 1",
    area_type: "semi-urban",
    population: 5200,
    ward_id: "w3",
    pincode: "201005",
    landmark: "Community Hall",
    households: 1040,
  },
  {
    area_id: "a10",
    area_name: "Sector 2",
    area_type: "semi-urban",
    population: 4800,
    ward_id: "w3",
    pincode: "201005",
    households: 960,
  },
  {
    area_id: "a11",
    area_name: "Green Colony",
    area_type: "semi-urban",
    population: 5400,
    ward_id: "w3",
    pincode: "201006",
    landmark: "Park Gate",
    households: 1080,
  },
  {
    area_id: "a12",
    area_name: "New Extension",
    area_type: "semi-urban",
    population: 4400,
    ward_id: "w3",
    pincode: "201006",
    households: 880,
  },
  {
    area_id: "a13",
    area_name: "Block A",
    area_type: "urban",
    population: 6100,
    ward_id: "w4",
    pincode: "201007",
    landmark: "College Road",
    households: 1220,
  },
  {
    area_id: "a14",
    area_name: "Block B",
    area_type: "urban",
    population: 5800,
    ward_id: "w4",
    pincode: "201007",
    households: 1160,
  },
  {
    area_id: "a15",
    area_name: "Block C",
    area_type: "urban",
    population: 7200,
    ward_id: "w4",
    pincode: "201008",
    landmark: "Hospital Gate",
    households: 1440,
  },
  {
    area_id: "a16",
    area_name: "Block D",
    area_type: "urban",
    population: 5500,
    ward_id: "w4",
    pincode: "201008",
    households: 1100,
  },
  {
    area_id: "a17",
    area_name: "Village Rampur",
    area_type: "rural",
    population: 4200,
    ward_id: "w5",
    pincode: "201010",
    landmark: "Panchayat Bhawan",
    households: 840,
  },
  {
    area_id: "a18",
    area_name: "Village Sultanpur",
    area_type: "rural",
    population: 3800,
    ward_id: "w5",
    pincode: "201010",
    households: 760,
  },
  {
    area_id: "a19",
    area_name: "Village Khanpur",
    area_type: "rural",
    population: 3600,
    ward_id: "w5",
    pincode: "201011",
    households: 720,
  },
  {
    area_id: "a20",
    area_name: "Mohalla 1",
    area_type: "semi-urban",
    population: 5300,
    ward_id: "w6",
    pincode: "201012",
    landmark: "Post Office",
    households: 1060,
  },
  {
    area_id: "a21",
    area_name: "Mohalla 2",
    area_type: "semi-urban",
    population: 5000,
    ward_id: "w6",
    pincode: "201012",
    households: 1000,
  },
  {
    area_id: "a22",
    area_name: "Mohalla 3",
    area_type: "semi-urban",
    population: 5500,
    ward_id: "w6",
    pincode: "201013",
    landmark: "Tehsil Office",
    households: 1100,
  },
  {
    area_id: "a23",
    area_name: "Mohalla 4",
    area_type: "semi-urban",
    population: 5500,
    ward_id: "w6",
    pincode: "201013",
    households: 1100,
  },
  {
    area_id: "a24",
    area_name: "Sector A",
    area_type: "urban",
    population: 6800,
    ward_id: "w7",
    pincode: "201014",
    landmark: "Main Park",
    households: 1360,
  },
  {
    area_id: "a25",
    area_name: "Sector B",
    area_type: "urban",
    population: 7200,
    ward_id: "w7",
    pincode: "201014",
    households: 1440,
  },
  {
    area_id: "a26",
    area_name: "Sector C",
    area_type: "urban",
    population: 6900,
    ward_id: "w7",
    pincode: "201015",
    landmark: "Shopping Mall",
    households: 1380,
  },
  {
    area_id: "a27",
    area_name: "Sector D",
    area_type: "urban",
    population: 6500,
    ward_id: "w7",
    pincode: "201015",
    households: 1300,
  },
  {
    area_id: "a28",
    area_name: "Old Tilak",
    area_type: "semi-urban",
    population: 6200,
    ward_id: "w8",
    pincode: "201016",
    landmark: "Bus Stand",
    households: 1240,
  },
  {
    area_id: "a29",
    area_name: "New Tilak",
    area_type: "semi-urban",
    population: 6300,
    ward_id: "w8",
    pincode: "201016",
    households: 1260,
  },
  {
    area_id: "a30",
    area_name: "Tilak Extension",
    area_type: "semi-urban",
    population: 6400,
    ward_id: "w8",
    pincode: "201017",
    households: 1280,
  },
  {
    area_id: "a31",
    area_name: "Enclave Phase 1",
    area_type: "urban",
    population: 5700,
    ward_id: "w9",
    pincode: "201018",
    landmark: "Main Gate",
    households: 1140,
  },
  {
    area_id: "a32",
    area_name: "Enclave Phase 2",
    area_type: "urban",
    population: 5600,
    ward_id: "w9",
    pincode: "201018",
    households: 1120,
  },
  {
    area_id: "a33",
    area_name: "Enclave Phase 3",
    area_type: "urban",
    population: 5900,
    ward_id: "w9",
    pincode: "201019",
    landmark: "Community Center",
    households: 1180,
  },
  {
    area_id: "a34",
    area_name: "Enclave Phase 4",
    area_type: "urban",
    population: 5500,
    ward_id: "w9",
    pincode: "201019",
    households: 1100,
  },
  {
    area_id: "a35",
    area_name: "Gram Panchayat 1",
    area_type: "rural",
    population: 4500,
    ward_id: "w10",
    pincode: "201020",
    landmark: "Village Well",
    households: 900,
  },
  {
    area_id: "a36",
    area_name: "Gram Panchayat 2",
    area_type: "rural",
    population: 4100,
    ward_id: "w10",
    pincode: "201020",
    households: 820,
  },
  {
    area_id: "a37",
    area_name: "Gram Panchayat 3",
    area_type: "rural",
    population: 4200,
    ward_id: "w10",
    pincode: "201021",
    landmark: "Temple Road",
    households: 840,
  },
  {
    area_id: "a38",
    area_name: "Gram Panchayat 4",
    area_type: "rural",
    population: 4000,
    ward_id: "w10",
    pincode: "201021",
    households: 800,
  },
];

export const MOCK_GRIEVANCES: Grievance[] = [
  {
    grievance_id: "GR-001",
    citizen_name: "Rakesh Yadav",
    citizen_phone: "9812345678",
    category: "road",
    description: "Large pothole on main road near market causing accidents",
    ward_id: "w1",
    assigned_dept: "PWD",
    priority: "high",
    status: "pending",
    created_date: "2026-02-10",
    created_by: "u3",
  },
  {
    grievance_id: "GR-002",
    citizen_name: "Sunita Devi",
    citizen_phone: "9812345679",
    category: "water",
    description: "No water supply for 3 days in Block C",
    ward_id: "w2",
    assigned_dept: "Jal Board",
    priority: "high",
    status: "in_progress",
    created_date: "2026-02-08",
    created_by: "u3",
  },
  {
    grievance_id: "GR-003",
    citizen_name: "Mohammad Aslam",
    citizen_phone: "9812345680",
    category: "electricity",
    description: "Street lights not working in lane 4-7",
    ward_id: "w3",
    assigned_dept: "Electricity Board",
    priority: "medium",
    status: "resolved",
    created_date: "2026-01-28",
    resolved_date: "2026-02-05",
    resolution_note: "All 12 street lights repaired and functional",
    created_by: "u4",
  },
  {
    grievance_id: "GR-004",
    citizen_name: "Anita Sharma",
    citizen_phone: "9812345681",
    category: "sanitation",
    description: "Garbage not collected for a week in sector 5",
    ward_id: "w4",
    assigned_dept: "Municipal Corp",
    priority: "medium",
    status: "pending",
    created_date: "2026-02-12",
    created_by: "u3",
  },
  {
    grievance_id: "GR-005",
    citizen_name: "Vijay Kumar",
    citizen_phone: "9812345682",
    category: "health",
    description: "Stagnant water breeding mosquitoes near school",
    ward_id: "w1",
    assigned_dept: "Health Dept",
    priority: "high",
    status: "in_progress",
    created_date: "2026-02-06",
    created_by: "u4",
  },
  {
    grievance_id: "GR-006",
    citizen_name: "Meena Kumari",
    citizen_phone: "9812345683",
    category: "education",
    description: "Roof leaking in primary school building",
    ward_id: "w5",
    assigned_dept: "Education Dept",
    priority: "medium",
    status: "pending",
    created_date: "2026-02-14",
    created_by: "u3",
  },
  {
    grievance_id: "GR-007",
    citizen_name: "Harish Chandra",
    citizen_phone: "9812345684",
    category: "road",
    description: "Speed breakers needed near hospital entrance",
    ward_id: "w6",
    assigned_dept: "PWD",
    priority: "low",
    status: "resolved",
    created_date: "2026-01-15",
    resolved_date: "2026-02-01",
    resolution_note: "Two speed breakers installed",
    created_by: "u4",
  },
  {
    grievance_id: "GR-008",
    citizen_name: "Fatima Begum",
    citizen_phone: "9812345685",
    category: "water",
    description: "Contaminated water supply in old town area",
    ward_id: "w7",
    assigned_dept: "Jal Board",
    priority: "high",
    status: "in_progress",
    created_date: "2026-02-09",
    created_by: "u3",
  },
  {
    grievance_id: "GR-009",
    citizen_name: "Suresh Patel",
    citizen_phone: "9812345686",
    category: "safety",
    description: "Broken boundary wall of community park",
    ward_id: "w8",
    assigned_dept: "Municipal Corp",
    priority: "low",
    status: "pending",
    created_date: "2026-02-13",
    created_by: "u4",
  },
  {
    grievance_id: "GR-010",
    citizen_name: "Kavita Singh",
    citizen_phone: "9812345687",
    category: "electricity",
    description: "Frequent power cuts lasting 4-5 hours daily",
    ward_id: "w2",
    assigned_dept: "Electricity Board",
    priority: "high",
    status: "pending",
    created_date: "2026-02-15",
    created_by: "u3",
  },
  {
    grievance_id: "GR-011",
    citizen_name: "Deepak Mishra",
    citizen_phone: "9812345688",
    category: "road",
    description: "Waterlogging on NH-24 bypass road",
    ward_id: "w9",
    assigned_dept: "PWD",
    priority: "medium",
    status: "in_progress",
    created_date: "2026-02-07",
    created_by: "u4",
  },
  {
    grievance_id: "GR-012",
    citizen_name: "Lakshmi Bai",
    citizen_phone: "9812345689",
    category: "sanitation",
    description: "Open drain overflowing near residential area",
    ward_id: "w10",
    assigned_dept: "Municipal Corp",
    priority: "high",
    status: "pending",
    created_date: "2026-02-11",
    created_by: "u3",
  },
];

export const MOCK_PROJECTS: Project[] = [
  {
    project_id: "PJ-001",
    project_name: "Shivaji Nagar Road Widening",
    category: "Infrastructure",
    department: "PWD",
    contractor_name: "Sharma Constructions",
    ward_id: "w1",
    start_date: "2025-06-01",
    end_date: "2026-06-01",
    budget_sanctioned: 25000000,
    budget_released: 18000000,
    budget_used: 14500000,
    status: "running",
    completion_percentage: 65,
    description: "Widening of main road from 20ft to 40ft",
  },
  {
    project_id: "PJ-002",
    project_name: "Gandhi Chowk Water Pipeline",
    category: "Water Supply",
    department: "Jal Board",
    contractor_name: "AquaPure Ltd",
    ward_id: "w2",
    start_date: "2025-03-15",
    end_date: "2025-12-31",
    budget_sanctioned: 12000000,
    budget_released: 12000000,
    budget_used: 11200000,
    status: "completed",
    completion_percentage: 100,
    description: "New water pipeline installation for 5000 households",
  },
  {
    project_id: "PJ-003",
    project_name: "Nehru Colony Community Center",
    category: "Social",
    department: "Municipal Corp",
    contractor_name: "BuildWell Infra",
    ward_id: "w3",
    start_date: "2025-09-01",
    end_date: "2026-09-01",
    budget_sanctioned: 8500000,
    budget_released: 5000000,
    budget_used: 3200000,
    status: "running",
    completion_percentage: 38,
    description: "Construction of community center with 500 capacity hall",
  },
  {
    project_id: "PJ-004",
    project_name: "Ambedkar Nagar Drainage System",
    category: "Infrastructure",
    department: "PWD",
    contractor_name: "Metro Drains Pvt Ltd",
    ward_id: "w4",
    start_date: "2026-01-15",
    end_date: "2026-12-31",
    budget_sanctioned: 15000000,
    budget_released: 5000000,
    budget_used: 1200000,
    status: "running",
    completion_percentage: 12,
    description: "Underground drainage system for entire ward",
  },
  {
    project_id: "PJ-005",
    project_name: "Patel Ward Primary School Renovation",
    category: "Education",
    department: "Education Dept",
    contractor_name: "EduBuild Solutions",
    ward_id: "w5",
    start_date: "2025-11-01",
    end_date: "2026-04-30",
    budget_sanctioned: 3500000,
    budget_released: 3500000,
    budget_used: 2800000,
    status: "running",
    completion_percentage: 78,
    description: "Complete renovation of government primary school",
  },
  {
    project_id: "PJ-006",
    project_name: "Solar Street Lights Installation",
    category: "Energy",
    department: "Electricity Board",
    contractor_name: "SunPower Systems",
    ward_id: "w6",
    start_date: "2025-08-01",
    end_date: "2026-02-28",
    budget_sanctioned: 6000000,
    budget_released: 6000000,
    budget_used: 5500000,
    status: "completed",
    completion_percentage: 100,
    description: "Installation of 200 solar street lights",
  },
  {
    project_id: "PJ-007",
    project_name: "Rajendra Nagar Park Development",
    category: "Social",
    department: "Municipal Corp",
    contractor_name: "GreenScape Designs",
    ward_id: "w7",
    start_date: "2026-03-01",
    end_date: "2026-10-31",
    budget_sanctioned: 4500000,
    budget_released: 0,
    budget_used: 0,
    status: "pending",
    completion_percentage: 0,
    description: "Development of 2-acre public park with jogging track",
  },
  {
    project_id: "PJ-008",
    project_name: "PHC Tilak Vihar Upgrade",
    category: "Health",
    department: "Health Dept",
    contractor_name: "MediBuild Corp",
    ward_id: "w8",
    start_date: "2025-10-01",
    end_date: "2026-03-31",
    budget_sanctioned: 7000000,
    budget_released: 7000000,
    budget_used: 4900000,
    status: "running",
    completion_percentage: 70,
    description: "Upgrade of Primary Health Centre to 30-bed facility",
  },
  {
    project_id: "PJ-009",
    project_name: "CCTV Surveillance Network",
    category: "Safety",
    department: "Police",
    contractor_name: "SecureTech India",
    ward_id: "w9",
    start_date: "2026-01-01",
    end_date: "2026-06-30",
    budget_sanctioned: 9000000,
    budget_released: 4000000,
    budget_used: 2500000,
    status: "running",
    completion_percentage: 30,
    description: "Installation of 150 CCTV cameras across the constituency",
  },
  {
    project_id: "PJ-010",
    project_name: "Bhagat Singh Colony Well Digging",
    category: "Water Supply",
    department: "Jal Board",
    contractor_name: "DeepWell Borings",
    ward_id: "w10",
    start_date: "2026-02-01",
    end_date: "2026-08-31",
    budget_sanctioned: 2000000,
    budget_released: 1000000,
    budget_used: 0,
    status: "on_hold",
    completion_percentage: 0,
    description:
      "Bore well digging for 3 villages - on hold due to land acquisition",
  },
];

export const MOCK_INSTITUTIONS: Institution[] = [
  {
    institution_id: "IN-001",
    name: "Shri Ram Mandir",
    inst_category: "temple",
    address: "Main Market, Shivaji Nagar",
    ward_id: "w1",
    official_contact_no: "9800000001",
    status: "active",
    established_year: 1952,
  },
  {
    institution_id: "IN-002",
    name: "District Hospital",
    inst_category: "hospital",
    address: "Civil Lines, Gandhi Chowk",
    ward_id: "w2",
    official_contact_no: "9800000002",
    email: "dh@health.gov.in",
    status: "active",
    established_year: 1978,
  },
  {
    institution_id: "IN-003",
    name: "Govt. Senior Secondary School",
    inst_category: "school",
    address: "Education Lane, Nehru Colony",
    ward_id: "w3",
    official_contact_no: "9800000003",
    status: "active",
    established_year: 1965,
  },
  {
    institution_id: "IN-004",
    name: "Ambedkar Degree College",
    inst_category: "college",
    address: "College Road, Ambedkar Nagar",
    ward_id: "w4",
    official_contact_no: "9800000004",
    status: "active",
    established_year: 1988,
  },
  {
    institution_id: "IN-005",
    name: "Sadar Police Station",
    inst_category: "police_station",
    address: "Main Road, Patel Ward",
    ward_id: "w5",
    official_contact_no: "100",
    status: "active",
    established_year: 1950,
  },
  {
    institution_id: "IN-006",
    name: "Tehsil Office",
    inst_category: "govt_office",
    address: "Tehsil Bhawan, Subhash Mohalla",
    ward_id: "w6",
    official_contact_no: "9800000006",
    status: "active",
    established_year: 1960,
  },
  {
    institution_id: "IN-007",
    name: "Seva Bharti NGO",
    inst_category: "ngo",
    address: "Rajendra Nagar Main Road",
    ward_id: "w7",
    official_contact_no: "9800000007",
    status: "active",
    established_year: 2005,
  },
  {
    institution_id: "IN-008",
    name: "Fitness Zone Gym",
    inst_category: "gym",
    address: "Market Complex, Tilak Vihar",
    ward_id: "w8",
    official_contact_no: "9800000008",
    status: "active",
    established_year: 2018,
  },
  {
    institution_id: "IN-009",
    name: "Sarojini Market",
    inst_category: "market",
    address: "Central Area, Sarojini Enclave",
    ward_id: "w9",
    official_contact_no: "9800000009",
    status: "active",
    established_year: 1975,
  },
  {
    institution_id: "IN-010",
    name: "Bhagat Singh Stadium",
    inst_category: "sports_ground",
    address: "Sports Complex Road",
    ward_id: "w10",
    official_contact_no: "9800000010",
    status: "under_maintenance",
    established_year: 1990,
  },
  {
    institution_id: "IN-011",
    name: "Primary Health Centre",
    inst_category: "dispensary",
    address: "Village Road, Patel Ward",
    ward_id: "w5",
    official_contact_no: "9800000011",
    status: "active",
    established_year: 1985,
  },
  {
    institution_id: "IN-012",
    name: "Masjid-e-Noor",
    inst_category: "temple",
    address: "Old Town, Gandhi Chowk",
    ward_id: "w2",
    official_contact_no: "9800000012",
    status: "active",
    established_year: 1920,
  },
];

// export const MOCK_SCHEMES: Scheme[] = [
//   {
//     scheme_id: "SC-001",
//     name: "Ayushman Bharat Yojana",
//     department: "Health Dept",
//     target_beneficiaries: 15000,
//     current_beneficiaries: 11200,
//     budget: 5000000,
//     status: "active",
//     ward_id: "w1",
//     description: "Free health coverage up to ₹5 lakh per family",
//     start_date: "2025-04-01",
//     end_date: "2026-03-31",
//   },
//   {
//     scheme_id: "SC-002",
//     name: "PM Awas Yojana",
//     department: "Housing Dept",
//     target_beneficiaries: 500,
//     current_beneficiaries: 320,
//     budget: 25000000,
//     status: "active",
//     ward_id: "w5",
//     description: "Affordable housing for economically weaker sections",
//     start_date: "2025-01-01",
//     end_date: "2027-12-31",
//   },
//   {
//     scheme_id: "SC-003",
//     name: "Beti Bachao Beti Padhao",
//     department: "Women & Child",
//     target_beneficiaries: 2000,
//     current_beneficiaries: 1450,
//     budget: 3000000,
//     status: "active",
//     ward_id: "w3",
//     description: "Girl child education and welfare program",
//     start_date: "2025-04-01",
//     end_date: "2026-03-31",
//   },
//   {
//     scheme_id: "SC-004",
//     name: "Swachh Bharat Mission",
//     department: "Municipal Corp",
//     target_beneficiaries: 8000,
//     current_beneficiaries: 6500,
//     budget: 8000000,
//     status: "active",
//     ward_id: "w4",
//     description: "Sanitation and cleanliness mission",
//     start_date: "2025-04-01",
//     end_date: "2026-03-31",
//   },
//   {
//     scheme_id: "SC-005",
//     name: "PM Kisan Samman Nidhi",
//     department: "Agriculture",
//     target_beneficiaries: 3000,
//     current_beneficiaries: 2100,
//     budget: 18000000,
//     status: "active",
//     ward_id: "w10",
//     description: "Direct income support of ₹6000/year to farmers",
//     start_date: "2025-04-01",
//     end_date: "2026-03-31",
//   },
// ];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    title: "New Grievance Filed",
    message: "High priority grievance GR-012 filed in Bhagat Singh Colony",
    type: "warning",
    is_read: false,
    created_at: "2026-02-16T09:30:00",
  },
  {
    id: "n2",
    title: "Project Milestone",
    message: "Patel Ward School Renovation reached 78% completion",
    type: "success",
    is_read: false,
    created_at: "2026-02-15T14:20:00",
  },
  {
    id: "n3",
    title: "Overdue Grievance",
    message: "GR-005 has been pending for over 10 days",
    type: "error",
    is_read: false,
    created_at: "2026-02-16T08:00:00",
  },
  {
    id: "n4",
    title: "Report Generated",
    message: "Monthly governance report for January 2026 is ready",
    type: "info",
    is_read: true,
    created_at: "2026-02-14T10:00:00",
  },
  {
    id: "n5",
    title: "Budget Released",
    message: "₹50L released for Ambedkar Nagar Drainage System",
    type: "success",
    is_read: true,
    created_at: "2026-02-13T16:45:00",
  },
];

// Chart data
export const GRIEVANCE_BY_CATEGORY = [
  { name: "Road", value: 28 },
  { name: "Water", value: 22 },
  { name: "Electricity", value: 18 },
  { name: "Sanitation", value: 15 },
  { name: "Health", value: 10 },
  { name: "Safety", value: 8 },
  { name: "Education", value: 6 },
  { name: "Other", value: 5 },
];

export const PROJECT_STATUS_DATA = [
  { name: "Completed", value: 2, fill: "hsl(160, 84%, 39%)" },
  { name: "Running", value: 5, fill: "hsl(217, 91%, 60%)" },
  { name: "Pending", value: 1, fill: "hsl(38, 92%, 50%)" },
  { name: "On Hold", value: 1, fill: "hsl(0, 84%, 60%)" },
];

export const MONTHLY_GRIEVANCE_TREND = [
  { month: "Mar", filed: 32, resolved: 28 },
  { month: "Apr", filed: 45, resolved: 38 },
  { month: "May", filed: 38, resolved: 35 },
  { month: "Jun", filed: 52, resolved: 42 },
  { month: "Jul", filed: 48, resolved: 45 },
  { month: "Aug", filed: 55, resolved: 48 },
  { month: "Sep", filed: 42, resolved: 40 },
  { month: "Oct", filed: 60, resolved: 50 },
  { month: "Nov", filed: 48, resolved: 46 },
  { month: "Dec", filed: 35, resolved: 33 },
  { month: "Jan", filed: 52, resolved: 44 },
  { month: "Feb", filed: 38, resolved: 25 },
];

export const DEPARTMENT_PERFORMANCE = [
  { dept: "PWD", score: 82 },
  { dept: "Jal Board", score: 75 },
  { dept: "Electricity", score: 88 },
  { dept: "Municipal", score: 70 },
  { dept: "Health", score: 91 },
  { dept: "Education", score: 85 },
];
