import { z } from "zod";

export const createTestSchema = z.object({
  title: z.string().min(1, "Title is required").max(255),
  duration: z.number().min(1, "Duration must be at least 1 minute"),
  totalQuestions: z.number().min(1, "Total questions must be at least 1"),
  totalMarks: z.number().optional().default(0),
  passingScore: z.number().optional().default(50),
  instructions: z.string().optional(),
  termsConditions: z.string().optional(),
  isActive: z.boolean().optional().default(true),
  startDate: z.string().datetime().optional().nullable(),
  endDate: z.string().datetime().optional().nullable(),
  allowedAttempts: z.number().optional().default(1),
  negativeMarking: z.boolean().optional().default(false),
  negativeMarkValue: z.number().optional().default(0),
  shuffleQuestions: z.boolean().optional().default(true),
  showResult: z.boolean().optional().default(true),
  showAnswers: z.boolean().optional().default(false),
  minAnswersRequired: z.number().optional().default(1),
  languageIds: z.array(z.string().min(1)).optional().default([]),
});

export const updateTestSchema = z.object({
  title: z.string().min(1).max(255).optional(),
  duration: z.number().min(1).optional(),
  totalQuestions: z.number().min(1).optional(),
  totalMarks: z.number().optional(),
  passingScore: z.number().optional(),
  instructions: z.string().optional(),
  termsConditions: z.string().optional(),
  isActive: z.boolean().optional(),
  startDate: z.string().datetime().optional().nullable(),
  endDate: z.string().datetime().optional().nullable(),
  allowedAttempts: z.number().optional(),
  negativeMarking: z.boolean().optional(),
  negativeMarkValue: z.number().optional(),
  shuffleQuestions: z.boolean().optional(),
  showResult: z.boolean().optional(),
  showAnswers: z.boolean().optional(),
  minAnswersRequired: z.number().optional(),
  languageIds: z.array(z.string().min(1)).optional(),
});
